# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'UAP' do
	pod 'Alamofire'
end

target 'UAPTests' do

end

target 'UAPUITests' do

end

